name: SharkWire (USA ???)
sha1: 3c35f73ac0a7e28ade7d754304b711636bc3657b
options:
  basename: loader
  target_path: baserom.z64
  elf_path: build/loader.elf
  base_path: ..
  platform: n64
  compiler: SN64

  asm_path: asm/loader
  src_path: src/loader
  build_path: build
  asset_path: assets/loader
  create_asm_dependencies: True

  ld_script_path: loader.ld
  ld_dependencies: True

  find_file_boundaries: True
  header_encoding: ASCII

  o_as_suffix: True
  use_legacy_include_asm: False
  mips_abi_float_regs: o32

  # asm_function_macro: glabel
  # asm_jtbl_label_macro: jlabel
  # asm_data_macro: dlabel

  section_order: [".text", ".rdata", ".rodata", ".sbss", ".bss", ".data"]
  # auto_link_sections: [".data", ".rodata", ".bss"]

  symbol_addrs_path:
    - symbol_addrs.txt
  reloc_addrs_path:
    - reloc_addrs.txt

  # undefined_funcs_auto_path: undefined_funcs_auto.txt
  # undefined_syms_auto_path: undefined_syms_auto.txt

  extensions_path: tools/splat_ext

  # string_encoding: ASCII
  # data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2
  # libultra_symbols: True
  # hardware_regs: True
  # gfx_ucode: # one of [f3d, f3db, f3dex, f3dexb, f3dex2]
  hasm_in_src_path: True
  named_regs_for_c_funcs: False
  migrate_rodata_to_functions: True
  pair_rodata_to_text: True
  ld_bss_is_noload: False
  ld_symbol_header_path: include/loader/linker.h
  add_set_gp_64: false
  ld_fill_value: 0xFFFFFFFF
segments:
  - name: header
    type: code
    start: 0x0
    vram: 0
    subsegments:
      - [0x0, hasm, header]

  - name: boot
    type: bin
    start: 0x40

  - name: loader
    type: code
    start: 0x1000
    vram: 0x80201000
    subsegments:
      - [0x1000, hasm, loader]

  - name: main
    type: code
    start: 0x10B0
    vram: 0x802010B0
    subsegments:
      - [0x10B0, c, eeprom]
      - [0x16A0, hasm, lz77]
      - [0x2930, c, main]
      - [0x2A00, c, update]
      - [0x2DC0, c, hw]
      - [0x2E90, hasm, util]
      - [0x2FE0, c, pi]
      - [0x30A0, c, si]
      - [0x3150, c, vi]
      - [0x3980, linker_offset]
      - { start: 0x3980, type: i4, name: font, width: 8, height: 1748, linker_section_order: ".rodata" }
      - { start: 0x54D0, type: bin, linker_section_order: ".rodata" }
      - [0x5530, .rdata, eeprom]
      - [0x5550, .rdata, update]
      - [0x57A0, .rdata, vi]
      - [0x5930, .sbss, main]
      - [0x5960, linker_offset]
      - [0x5960, lz77, lz77, browser]
      - [0xCBD00, .data, update]
      - [0xCBD50, .data, hw]
      - [0xCBD60, pad]
      - [0xE0000, bin]

  - [0x100000]
